name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run migrate
      - run: npm run test:e2e

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Docker image
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nest-api-ci:${{ steps.generate_tag.outputs.sha }} .

      # - name: Push image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nest-api-ci:${{ steps.generate_tag.outputs.sha }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nest-api-ci:${{ steps.generate_tag.outputs.sha }},${{ secrets.DOCKERHUB_USERNAME }}/nest-api-ci:latest

    env:
      DATABASE_URL: "postgresql://postgres:docker@localhost:5432/test?schema=public"
